# Generated by Django 4.0 on 2024-03-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postmaiking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='imag',
            field=models.ImageField(upload_to='media/', verbose_name='image'),
        ),
    ]
